apiVersion: v1
kind: ConfigMap
metadata:
  name: task-api-config
  namespace: task-api
data:
  APP_PORT: "3000"
  APP_VERSION: "1.0.0"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: task-api-secret
  namespace: task-api
type: Opaque
stringData:
  REDIS_PASSWORD: "minhasenhaforte"